version: 2
jobs:
  build:
    environment:
      ENV: dev
      BUNDLE_APP_CONFIG: ~/project/.bundle
      DATABASE_URL: postgres://root@0.0.0.0:5432/circle-test_test
    docker:
      - image: circleci/ruby:2.5.3-node
      - image: circleci/postgres
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle-test_test
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dep-{{ .Branch }}-
            - v1-dep-master-
            - v1-dep-
      - run:
          name: 'Install gems'
          command: |
            bundle install
      - save_cache:
          key: v1-dep-{{ .Branch }}-{{ epoch }}
          paths:
            - vendor/bundle
      - run:
          name: 'Ruby: Run tests'
          command: |
            bundle exec rake
      - store_test_results:
          path: /tmp/circleci-test-results
      - store_artifacts:
          path: /tmp/circleci-artifacts
